(IN-PACKAGE :CL-LOG)
(DEFUN FUNCTION-0 (PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LOG-DEBUG "PARAMETER-0=~a" PARAMETER-0)
  (LOG-DEBUG "PARAMETER-1=~a" PARAMETER-1)
  (LOG-DEBUG "PARAMETER-2=~a" PARAMETER-2)
  (LOG-DEBUG "PARAMETER-3=~a" PARAMETER-3)
  (LOG-DEBUG "PARAMETER-4=~a" PARAMETER-4)
  (LOG-DEBUG
   "PARAMETER-0=~a PARAMETER-1=~a PARAMETER-2=~a PARAMETER-3=~a PARAMETER-4=~a"
   PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LIST PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4))
(DEFUN FUNCTION-1 (PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LOG-DEBUG "PARAMETER-0=~a" PARAMETER-0)
  (LOG-DEBUG "PARAMETER-1=~a" PARAMETER-1)
  (LOG-DEBUG "PARAMETER-2=~a" PARAMETER-2)
  (LOG-DEBUG "PARAMETER-3=~a" PARAMETER-3)
  (LOG-DEBUG "PARAMETER-4=~a" PARAMETER-4)
  (LOG-DEBUG
   "PARAMETER-0=~a PARAMETER-1=~a PARAMETER-2=~a PARAMETER-3=~a PARAMETER-4=~a"
   PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LIST PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4))
(DEFUN FUNCTION-2 (PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LOG-DEBUG "PARAMETER-0=~a" PARAMETER-0)
  (LOG-DEBUG "PARAMETER-1=~a" PARAMETER-1)
  (LOG-DEBUG "PARAMETER-2=~a" PARAMETER-2)
  (LOG-DEBUG "PARAMETER-3=~a" PARAMETER-3)
  (LOG-DEBUG "PARAMETER-4=~a" PARAMETER-4)
  (LOG-DEBUG
   "PARAMETER-0=~a PARAMETER-1=~a PARAMETER-2=~a PARAMETER-3=~a PARAMETER-4=~a"
   PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LIST PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4))
(DEFUN FUNCTION-3 (PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LOG-DEBUG "PARAMETER-0=~a" PARAMETER-0)
  (LOG-DEBUG "PARAMETER-1=~a" PARAMETER-1)
  (LOG-DEBUG "PARAMETER-2=~a" PARAMETER-2)
  (LOG-DEBUG "PARAMETER-3=~a" PARAMETER-3)
  (LOG-DEBUG "PARAMETER-4=~a" PARAMETER-4)
  (LOG-DEBUG
   "PARAMETER-0=~a PARAMETER-1=~a PARAMETER-2=~a PARAMETER-3=~a PARAMETER-4=~a"
   PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LIST PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4))
(DEFUN FUNCTION-4 (PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LOG-DEBUG "PARAMETER-0=~a" PARAMETER-0)
  (LOG-DEBUG "PARAMETER-1=~a" PARAMETER-1)
  (LOG-DEBUG "PARAMETER-2=~a" PARAMETER-2)
  (LOG-DEBUG "PARAMETER-3=~a" PARAMETER-3)
  (LOG-DEBUG "PARAMETER-4=~a" PARAMETER-4)
  (LOG-DEBUG
   "PARAMETER-0=~a PARAMETER-1=~a PARAMETER-2=~a PARAMETER-3=~a PARAMETER-4=~a"
   PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LIST PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4))
(DEFUN FUNCTION-5 (PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LOG-DEBUG "PARAMETER-0=~a" PARAMETER-0)
  (LOG-DEBUG "PARAMETER-1=~a" PARAMETER-1)
  (LOG-DEBUG "PARAMETER-2=~a" PARAMETER-2)
  (LOG-DEBUG "PARAMETER-3=~a" PARAMETER-3)
  (LOG-DEBUG "PARAMETER-4=~a" PARAMETER-4)
  (LOG-DEBUG
   "PARAMETER-0=~a PARAMETER-1=~a PARAMETER-2=~a PARAMETER-3=~a PARAMETER-4=~a"
   PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LIST PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4))
(DEFUN FUNCTION-6 (PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LOG-DEBUG "PARAMETER-0=~a" PARAMETER-0)
  (LOG-DEBUG "PARAMETER-1=~a" PARAMETER-1)
  (LOG-DEBUG "PARAMETER-2=~a" PARAMETER-2)
  (LOG-DEBUG "PARAMETER-3=~a" PARAMETER-3)
  (LOG-DEBUG "PARAMETER-4=~a" PARAMETER-4)
  (LOG-DEBUG
   "PARAMETER-0=~a PARAMETER-1=~a PARAMETER-2=~a PARAMETER-3=~a PARAMETER-4=~a"
   PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LIST PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4))
(DEFUN FUNCTION-7 (PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LOG-DEBUG "PARAMETER-0=~a" PARAMETER-0)
  (LOG-DEBUG "PARAMETER-1=~a" PARAMETER-1)
  (LOG-DEBUG "PARAMETER-2=~a" PARAMETER-2)
  (LOG-DEBUG "PARAMETER-3=~a" PARAMETER-3)
  (LOG-DEBUG "PARAMETER-4=~a" PARAMETER-4)
  (LOG-DEBUG
   "PARAMETER-0=~a PARAMETER-1=~a PARAMETER-2=~a PARAMETER-3=~a PARAMETER-4=~a"
   PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LIST PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4))
(DEFUN FUNCTION-8 (PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LOG-DEBUG "PARAMETER-0=~a" PARAMETER-0)
  (LOG-DEBUG "PARAMETER-1=~a" PARAMETER-1)
  (LOG-DEBUG "PARAMETER-2=~a" PARAMETER-2)
  (LOG-DEBUG "PARAMETER-3=~a" PARAMETER-3)
  (LOG-DEBUG "PARAMETER-4=~a" PARAMETER-4)
  (LOG-DEBUG
   "PARAMETER-0=~a PARAMETER-1=~a PARAMETER-2=~a PARAMETER-3=~a PARAMETER-4=~a"
   PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LIST PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4))
(DEFUN FUNCTION-9 (PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LOG-DEBUG "PARAMETER-0=~a" PARAMETER-0)
  (LOG-DEBUG "PARAMETER-1=~a" PARAMETER-1)
  (LOG-DEBUG "PARAMETER-2=~a" PARAMETER-2)
  (LOG-DEBUG "PARAMETER-3=~a" PARAMETER-3)
  (LOG-DEBUG "PARAMETER-4=~a" PARAMETER-4)
  (LOG-DEBUG
   "PARAMETER-0=~a PARAMETER-1=~a PARAMETER-2=~a PARAMETER-3=~a PARAMETER-4=~a"
   PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4)
  (LIST PARAMETER-0 PARAMETER-1 PARAMETER-2 PARAMETER-3 PARAMETER-4))
